//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 03:05:44 PM EET 
//

package epam.trainig.xmlTask.convertedFromXsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Consistence.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Consistence">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TABLETS"/>
 *     &lt;enumeration value="CAPSULES"/>
 *     &lt;enumeration value="POWDERS"/>
 *     &lt;enumeration value="DROPS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Consistence")
@XmlEnum
public enum Consistence {

	TABLETS, CAPSULES, POWDERS, DROPS;

	public String value() {
		return name();
	}

	public static Consistence fromValue(String v) {
		return valueOf(v);
	}

}
