//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 03:05:44 PM EET 
//

package epam.trainig.xmlTask.convertedFromXsd;

import java.util.ArrayList;
import java.util.List;

/**
 * 
 * Java class for Drug complex type from XML document. Contains field which
 * matches information from Drug complex type from XML.
 * 
 */

public class Drug {

	private String name;

	private String pharm;

	private String group;

	private List<String> analogs;

	private List<Version> versions;

	private String id;

	private String country;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		name = value;
	}

	/**
	 * Gets the value of the pharm property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPharm() {
		return pharm;
	}

	/**
	 * Sets the value of the pharm property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPharm(String value) {
		pharm = value;
	}

	/**
	 * Gets the value of the group property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public String getGroup() {

		return group;
	}

	/**
	 * Sets the value of the group property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setGroup(String value) {

		group = value;
	}

	/**
	 * Gets the value of the analogs property.
	 * 
	 * 
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 *    getAnalogs().add(newItem);
	 * Objects of the following type(s) are allowed in the list
	 * {@link String }
	 * 
	 * 
	 */
	public List<String> getAnalogs() {
		if (analogs == null) {
			analogs = new ArrayList<String>();
		}
		return analogs;
	}

	/**
	 * Gets the value of the versions property.
	 * 
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 *    getVersions().add(newItem);
	 *   
	 * Objects of the following type(s) are allowed in the list
	 * {@link Version }
	 * 
	 * 
	 */
	public List<Version> getVersions() {
		if (versions == null) {
			versions = new ArrayList<Version>();
		}
		return versions;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountry(String value) {
		country = value;
	}

	public String toString() {
		return ("\nDRUG  " + getId() + "  " + getCountry() + " " + "\n NAME= "
				+ getName() + " " + "\n GROuP= " + getGroup() + "\n PHARM= "
				+ getPharm() + "\n ANALOGS=" + getAnalogs() + "\n VERSIONS "
				+ getVersions() + "\n");
	}
}
