//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 03:05:44 PM EET 
//

package epam.trainig.xmlTask.convertedFromXsd;

import java.util.ArrayList;

import java.util.List;

/**
 * Class Medicine contains list of of objects Drug
 */
public class Medicine {

	private List<Drug> drugs;

	public Medicine() {
		drugs = new ArrayList<Drug>();
	}

	/**
	 * Gets the value of the drug property.
	 * 
	 * Objects of the following type(s) are allowed in the list {@link Drug }
	 */
	public List<Drug> getDrugs() {
		return drugs;

	}

	/**
	 * Adds new drug object to druds list
	 * 
	 * @param d
	 *            new drug which adds to list of drugs
	 */
	public void addDrug(Drug d) {
		drugs.add(d);

	}

	public String toString() {
		return drugs.toString();
	}

}
