//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 03:05:44 PM EET 
//

package epam.trainig.xmlTask.convertedFromXsd;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Version }
	 * 
	 */
	public Version createVersion() {
		return new Version();
	}

	/**
	 * Create an instance of {@link Medicine }
	 * 
	 */
	public Medicine createMedicine() {
		return new Medicine();
	}

	/**
	 * Create an instance of {@link Drug }
	 * 
	 */
	public Drug createDrug() {
		return new Drug();
	}

	/**
	 * Create an instance of {@link Version.Certificate }
	 * 
	 */
	public Version.Certificate createVersionCertificate() {
		return new Version.Certificate();
	}

	/**
	 * Create an instance of {@link Version.Package }
	 * 
	 */
	public Version.Package createVersionPackage() {
		return new Version.Package();
	}

	/**
	 * Create an instance of {@link Version.Dosage }
	 * 
	 */
	public Version.Dosage createVersionDosage() {
		return new Version.Dosage();
	}

}
