//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 03:05:44 PM EET 
//

package epam.trainig.xmlTask.convertedFromXsd;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Version complex type from XML document. Contains field which
 * matches information from Version complex type from XML.
 * 
 */

public class Version {

	protected Version.Certificate certificate;
	protected Version.Package _package;
	protected Version.Dosage dosage;
	protected String number;
	protected String consistence;
	protected String pharm;

	/**
	 * Gets the value of the certificate property.
	 * 
	 * @return possible object is {@link Version.Certificate }
	 * 
	 */
	public Version.Certificate getCertificate() {
		return certificate;
	}

	/**
	 * Sets the value of the certificate property.
	 * 
	 * @param value
	 *            allowed object is {@link Version.Certificate }
	 * 
	 */
	public void setCertificate(Version.Certificate value) {
		certificate = value;
	}

	/**
	 * Gets the value of the package property.
	 * 
	 * @return possible object is {@link Version.Package }
	 * 
	 */
	public Version.Package getPackage() {
		return _package;
	}

	/**
	 * Sets the value of the package property.
	 * 
	 * @param value
	 *            allowed object is {@link Version.Package }
	 * 
	 */
	public void setPackage(Version.Package value) {
		this._package = value;
	}

	/**
	 * Gets the value of the dosage property.
	 * 
	 * @return possible object is {@link Version.Dosage }
	 * 
	 */
	public Version.Dosage getDosage() {
		return dosage;
	}

	/**
	 * Sets the value of the dosage property.
	 * 
	 * @param value
	 *            allowed object is {@link Version.Dosage }
	 * 
	 */
	public void setDosage(Version.Dosage value) {
		dosage = value;
	}

	/**
	 * Gets the value of the number property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumber(String value) {
		number = value;
	}

	/**
	 * Gets the value of the consistence property.
	 * 
	 * @return possible object is {@link Consistence }
	 * 
	 */
	public String getConsistence() {
		return consistence;
	}

	/**
	 * Sets the value of the consistence property.
	 * 
	 * @param value
	 *            allowed object is {@link Consistence }
	 * 
	 */
	public void setConsistence(String value) {
		consistence = value;
	}

	/**
	 * Gets the value of the pharm property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPharm() {
		return pharm;
	}

	/**
	 * Sets the value of the pharm property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPharm(String value) {
		pharm = value;
	}

	/**
	 * 
	 * Java class that keeps information taken from tag <certificate> .
	 * 
	 * 
	 */
	public static class Certificate {

		protected String number;

		protected String issuedate;

		protected String expdate;

		protected String regOrganization;

		/**
		 * Gets the value of the number property.
		 * 
		 * @return possible object is {@link BigStringeger }
		 * 
		 */
		public String getNumber() {
			return number;
		}

		/**
		 * Sets the value of the number property.
		 * 
		 * @param value
		 *            allowed object is {@link BigStringeger }
		 * 
		 */
		public void setNumber(String value) {
			number = value;
		}

		/**
		 * Gets the value of the issuedate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public String getIssuedate() {
			return issuedate;
		}

		/**
		 * Sets the value of the issuedate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setIssuedate(String value) {
			issuedate = value;
		}

		/**
		 * Gets the value of the expdate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public String getExpdate() {
			return expdate;
		}

		/**
		 * Sets the value of the expdate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setExpdate(String value) {
			expdate = value;
		}

		/**
		 * Gets the value of the regOrganization property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRegOrganization() {
			return regOrganization;
		}

		/**
		 * Sets the value of the regOrganization property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRegOrganization(String value) {
			regOrganization = value;
		}

		@Override
		public String toString() {

			return " certificate " + getNumber() + " " + getIssuedate() + " "
					+ getExpdate() + " " + getRegOrganization();
		}

	}

	/**
	 * Java class that keeps information taken from tag <dosage>
	 */

	public static class Dosage {

		protected String value;

		protected String period;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the period property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPeriod() {
			return period;
		}

		/**
		 * Sets the value of the period property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPeriod(String value) {
			period = value;
		}

		@Override
		public String toString() {

			return " dosage " + getValue() + "  " + getPeriod();
		}

	}

	/**
	 * 
	 * Java class that keeps information taken from tag <package>
	 * 
	 * 
	 */

	public static class Package {

		protected String top;

		protected String amount;

		protected String price;

		/**
		 * Gets the value of the top property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTop() {
			return top;
		}

		/**
		 * Sets the value of the top property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTop(String value) {
			top = value;
		}

		/**
		 * Gets the value of the amount property.
		 * 
		 * @return possible object is {@link BigStringeger }
		 * 
		 */
		public String getAmount() {
			return amount;
		}

		/**
		 * Sets the value of the amount property.
		 * 
		 * @param value
		 *            allowed object is {@link BigStringeger }
		 * 
		 */
		public void setAmount(String value) {
			amount = value;
		}

		/**
		 * Gets the value of the price property.
		 * 
		 */
		public String getPrice() {
			return price;
		}

		/**
		 * Sets the value of the price property.
		 * 
		 */
		public void setPrice(String value) {
			price = value;
		}

		@Override
		public String toString() {

			return " package " + getTop() + " " + getAmount() + " "
					+ getPrice() + "grn ";
		}

	}

	public String toString() {
		return ("\n   version  " + getNumber() + "  " + getConsistence() + "  "
				+ getPharm() + "\n     " + getCertificate())
				+ "\n     " + getPackage() + "\n     " + getDosage();
	}

}
